### ISSUE TITLE
block is executed too often

### ISSUE THREAD

**Issue by andreas-s** [schleyfox/peach#1]
<pre>
ruby -e 'require "peach"; (1..10).to_a.peach{|x| sleep 0.01*x; puts x; sleep 1}'
</pre>

Expected result:

<pre>
1
2
3
4
5
6
7
8
9
10
</pre>

Actual result:

<pre>
1
2
3
4
5
6
7
8
9
10
2
3
4
5
6
1
7
8
9
10
</pre>

Reproduced with:
ruby 1.8.7 (2008-08-11 patchlevel 72) [x86_64-linux] 
jruby 1.5.2 (ruby 1.8.7 patchlevel 249) (2010-08-20 1c5e29d) (OpenJDK 64-Bit Server VM 1.6.0_0) [amd64-java]

**Comment by andreas-s** [comment]
fixed in https://github.com/bruceadams/peach/commit/3281f178b6ece85a6baab1e42e290d3a1435dd11

**Comment by schleyfox** [comment]
yeah, I've been kind of out at sea maintenance wise, but once I get jruby set up again on my development machine I will be merging in that branch as well as trying to address a few other concerns that I have been meaning to get to.

**Comment by schleyfox** [comment]
ok, merged in bruce adam's changes
